### ISSUE TITLE
Activation failed

### ISSUE THREAD

**Issue by ADPDaniel** [FriendsOfShopware/FroshPlatformWebP#4]
Hi @shyim ,

it is currently not possible to activate your plugin in shopware 6.3.5.0.

Argument 1 passed to Frosh\WebP\Services\TemplateLoader::__construct() must be an instance of Symfony\Bundle\TwigBundle\Loader\NativeFilesystemLoader, instance of Twig\Loader\ChainLoader given, called in [...] ContainerRrxibIL/srcShopware_Production_KernelProdContainer.php on line 18057

Do you have a fix for that?

Thank you :)
Daniel

**Comment by shyim** [comment]
Hey,

this Plugin was a prototype. I decided not to work on it anymore. So I close this.
